export const GET_DEVICES_CHANNEL = 'GET_DEVICES_CHANNEL';
export const CONNECT_DEVICE_CHANNEL = 'CONNECT_DEVICE_CHANNEL';
export const PING_DEVICE_CHANNEL = 'PING_DEVICE_CHANNEL';
export const SET_LED_MODE_CHANNEL = 'SET_LED_MODE_CHANNEL';
export const SET_LED_HSV_CHANNEL = 'SET_LED_HSV_CHANNEL';
